Workout.create(name:"Baby Steps")
Workout.create(name:"On the Road")
Workout.create(name:"WTF?!")

Exercise.create(name: "Plank Press", description: "Place dumbbells at top of mat, then get into full push-up position with arms shoulder-width apart and hands directly under shoulders; step feet out slightly wider than shoulder-width. Keeping hips level, lift right hand and pick up one dumbbell; drive right elbow backward at shoulder level, keeping arm close to side and palm facing down. Extend right arm forward. Return right elbow to bent position and repeat.", target_zone: "arms" , intensity: "easy", workout_id:1)
Exercise.create(name: "Russian Twist", description: "Grab a medicine ball, dumbbell, or weight plate and sit on the floor with your hips and knees bent 90 degrees. Hold the weight straight out in front of you and keep your back straight (your torso should be at about 45 degrees to the floor). Explosively twist your torso as far as you can to the left [1], and then reverse the motion, twisting as far as you can to the right [2]. That's one rep, do 3 sets of 8-12 at the end of your workout.", target_zone: "abs" , intensity: "intermediate", workout_id:1)
Exercise.create(name: "Burpee", description: "Stand straight, then lower into a squat position with your hands on the floor in front of you. Kick your feet back into a push-up position and immediately drop your chest to the floor. Bow your chest up as you return your feet back to the squat position as fast as possible. Jump up into the air as high as you can. Add a little clap for pizazz!", target_zone: "entire body" , intensity: "intermediate", workout_id:1)

Exercise.create(name: "Spiderman Pushup", description: "Assume the standard pushup position. As you lower your body toward the floor, lift your right foot off the floor, swing your right leg out sideways, and try to touch your knee to your elbow. Reverse the movement, then push your body back to the starting position. Repeat, but on your next repetition, touch your left knee to your left elbow. Continue to alternate back and forth.", target_zone: "upper body" , intensity: "hard", workout_id:2)
Exercise.create(name: "Running Pyramid", description: "Run in place for two steps (left, right), lifting knees to hip-level and letting arms swing naturally. Pause for 1 second. Repeat, this time taking three high-knee steps in place (left, right, left) before pausing for 1 second. Continue, adding one additional step each time.", target_zone: "entire body" , intensity: "intermediate", workout_id:2)
Exercise.create(name: "Tuck Jump", description: "Stand with feet hip width, arms by sides, knees slightly bent. Jump straight up, bending knees in front of hips, tapping tops of thighs with hands. Complete as many as you can in 45 seconds.", target_zone: "lower body" , intensity: "easy", workout_id:2)

Exercise.create(name: "Saddlebag Scorcher", description: "Begin on all fours, knees under hips and hands under shoulders. Place left forearm on floor so that left hand is perpendicular to right hand; twist torso slightly to the right and lift right leg just off floor. Keeping right knee bent 90 degrees throughout, raise right leg out to hip height. Lower leg under hip without letting it touch floor; repeat. Do 20 reps, switch sides and repeat. Do 3 sets. MAKE IT EASIER: Bring leg only 45 degrees out to side.", target_zone: "ass" , intensity: "hard", workout_id:3)
Exercise.create(name: "Plank Tuck", description: "Lie facedown on top of a Swiss ball. Walk arms out to a plank position with shins and tops of feet pressed into the ball and toes pointed. Bend knees and lift hips up, tucking knees into chest. Return to plank position.", target_zone: "abs" , intensity: "hard", workout_id:3)
Exercise.create(name: "Burpee", description: "Stand straight, then lower into a squat position with your hands on the floor in front of you. Kick your feet back into a push-up position and immediately drop your chest to the floor. Bow your chest up as you return your feet back to the squat position as fast as possible. Jump up into the air as high as you can. Add a little clap for pizazz!", target_zone: "entire body" , intensity: "intermediate", workout_id:3)

